version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./data/omekalakeland.sql.gz:/docker-entrypoint-initdb.d/dump.sql.gz
    environment:
      MYSQL_ROOT_PASSWORD: someomeka
      MYSQL_DATABASE: omekadblakeland
      MYSQL_USER: omekausername
      MYSQL_PASSWORD: omekapassword

  web:
    depends_on:
      - db
    build: ./apache
    volumes:
      - ./data/lakeland:/var/www/html
    ports:
      - "8000:80"
    restart: always
